server:
  port: 8081
  servlet:    context-path: /bnsapp
spring:  jpa:    generate-ddl: false    show-sql: true    properties:      dialect: org.hibernate.dialect.MySQL57Dialect  datasource:    hikari:      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 3000    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mysql
---
spring:  profiles: test  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: fuel
    password: mdtfuel
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe  jpa:    properties:      dialect: org.hibernate.dialect.OracleDialect